fix: crash if the id tool fails to run in the container (1660)

diff --git a/pkg/runner/testdata/remote-action-js-node-user/push.yml b/pkg/runner/testdata/remote-action-js-node-user/push.yml
--- a/pkg/runner/testdata/remote-action-js-node-user/push.yml
+++ b/pkg/runner/testdata/remote-action-js-node-user/push.yml
@@ -8,6 +8,21 @@ jobs:
       image: node:16-buster-slim
       options: --user node
     steps:
+    - name: check permissions of env files
+      id: test
+      run: |
+        echo "USER: $(id -un) expected: node"
+        [[ "$(id -un)" = "node" ]]
+        echo "TEST=Value" >> $GITHUB_OUTPUT
+      shell: bash
+
+    - name: check if file command worked
+      if: steps.test.outputs.test != 'Value'
+      run: |
+        echo "steps.test.outputs.test=${{ steps.test.outputs.test || 'missing value!' }}"
+        exit 1
+      shell: bash
+
     - uses: actions/hello-world-javascript-action@v1
       with:
         who-to-greet: 'Mona the Octocat'
